name: CI

on:
  push:
    branches:
      - '*' # todos los branches (idealmente se pushearía solo a staging)
  pull_request:
    branches:
      - main # integración a main

jobs:
  compilar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.3.1

      - name: Preparar Node.js
        uses: actions/setup-node@v6.0.0

      - name: Instalar
        run: npm install

      - name: Compilar
        run: npm run build
